### ISSUE TITLE
no requirement.txt

### ISSUE THREAD

**Issue by srini1603** [Tejaswi-Kumar/Two-way-Sign-Language-Translator#1]
can you please add requirement.txt because some packages you used aren't support and not offical pacakage from pypi like speech_recognition , gTTs it could be so helpfull if you added a requirement.txt

**Comment by srini1603** [comment]
numpy~=1.23.3
opencv-python~=4.6.0.66
keras~=2.6.0
easygui~=0.98.3
pillow~=9.2.0
pygame~=2.1.2
gtts~=2.2.4
pyaudio~=0.2.11
keras~=2.6.0
tensorflow~=2.10.0

**Comment by srini1603** [comment]
for anyone using this project in future i hope this will work

**Comment by Tejaswi-Kumar** [comment]
Hey @srini1603, thank you for your suggestion and solution, will add to the repo in a while.

**Comment by Tejaswi-Kumar** [comment]
Added the requirements.txt file, thanks for the suggestion again! Closing this issue now.
